### ISSUE TITLE
Build issue with Qt

### ISSUE THREAD

**Issue by dvd73** [BowDown097/QtTube#14]
Hi

One thing I've found while building this project. CMake stops with errors like this:
```
CMake Error at lib/innertube-qt/lib/http/CMakeLists.txt:40 (target_link_libraries):
  Target "http" links to:

    Qt::Core
```
The solution is: open pointed file and replace Qt::Core -> Qt5::Core and so on.

**Comment by BowDown097** [comment]
I will probably make that change, but that should be a valid target since Qt 5.15 (which I thought was the only Qt 5 version that this project even compiles under) according to [this page](https://doc.qt.io/qt-6/cmake-qt5-and-qt6-compatibility.html). Are you using an older Qt version?
