### ISSUE TITLE
How to make .exe for Win11?

### ISSUE THREAD

**Issue by vasmarfas** [BowDown097/QtTube#8]
Hello. I ran into a problem that I can not build this project for Win11. I installed Qt6, cmake, wingw, but I can't build it. Can you please provide a step by step guide for non-C users?

**Comment by BowDown097** [comment]
Your problem most likely stems from the fact that MinGW doesn't support Qt WebEngine, which is used by default. I should probably have a section for this in the README, so my bad.

If you can, I highly recommend you just use MSVC instead and it should work perfectly fine.

But if you really want to use MinGW, then you can:
- Turn the `QTTUBE_USE_MPV` option in the `CMakeLists.txt` file ON to use the MPV-based player, which is unmaintained for now and probably doesn't work.
- Turn the `INNERTUBE_NO_WEBENGINE` option in the `lib/innertube-qt/CMakeLists.txt` file ON, which will require you to provide login credentials manually should you wish to log in, steps are in [the innertube-qt project's wiki](https://github.com/BowDown097/innertube-qt/wiki/Manually-getting-login-credentials).

**Comment by vasmarfas** [comment]
I installed MSVC (my first-time using) and got this error:
```
Серьезность	Код	Описание	Проект	Файл	Строка	Состояние подавления
Ошибка		CMake Error at C:\Users\seel2304\source\repos\QtTube\CMakeLists.txt:45 (find_package):
  Could not find a package configuration file provided by "QT" with any of
  the following names:

    Qt6Config.cmake
    qt6-config.cmake
    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "QT" to CMAKE_PREFIX_PATH or set "QT_DIR" to
  a directory containing one of the above files.  If "QT" provides a separate
  development package or SDK, be sure it has been installed.	QtTube	C:\Users\seel2304\source\repos\QtTube\CMakeLists.txt	45	

```

![image](https://github.com/BowDown097/QtTube/assets/37144504/f6587009-7436-43a9-b112-1f78ea521204)

But i have installed Qt6, why it's happening? How to fix it?

**Comment by BowDown097** [comment]
Oh I got that at first too, restarting fixed it for me.

**Comment by vasmarfas** [comment]
I made fork and compiled installer for Windows. You can add it to releases page)
